name: "ALKiln: Automated docassemble tests"
description: "Automatically test any docassemble interview in a any branch on your GitHub repository whenever you commit or push. See https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/automated_integrated_testing."

inputs:
  SERVER_URL:
    description: 'The url of your docassemble server. This should be in your GitHub SECRETS or the SECRETS of your org.'
    required: true
  DOCASSEMBLE_DEVELOPER_API_KEY:
    description: 'API key of the testing account with developer permissions on your docassemble server.'
    required: true
  # This is necessary to test pre-releases at the very least. It does seem
  # strange considering we're controlling everything through the action, but
  # that actually doesn't touch the npm version that's pulled in.
  ALKILN_VERSION:
    description: 'Version of ALKiln to get from npm.'
    required: false
    default: '^5.0.0'
  MAX_SECONDS_FOR_SETUP:
    description: "Amount of time to give the Project to upload your package's GitHub code."
    required: false
    # Default in code below is 30 because it's needed by installation
  SERVER_RELOAD_TIMEOUT_SECONDS:
    description: "Max amount of time to give the server to reload if it needs to"
    required: false
    # no default to let the custom Scenario timeouts create the reload timeout
  # INSTALL_LOCATION? Will that get confused with the location passed into the command line?
  # Maybe `INSTALL_LOCATION` could be "playground", "server", or a custom path and we could handle all those.
  INSTALL_METHOD:
    description: "Default is 'playground'. Other option: 'server'. How to install the package onto the server."
    required: false
    default: "playground"
  ALKILN_TAG_EXPRESSION:
    description: "The tag expression to use to limit which tests to run. Default is no tag expression."
    required: false

runs:
  using: "composite"
  steps:
    # Place the root directory in this branch
    - uses: actions/checkout@v3

    # Set environment variables
    - name: "ALKiln setup info: Set environment variables"
      # Human-readable date/time:
      # https://www.shell-tips.com/linux/how-to-format-date-and-time-in-linux-macos-and-bash/#how-to-format-a-date-in-bash
      run: |
        # ALKiln setup info: Set environment variables
        echo "ARTIFACT_NAME=alkiln-$(date +'%Y-%m-%d at %Hh%Mm%Ss' -u)UTC" >> $GITHUB_ENV
        echo "REPO_URL=${{ github.server_url }}/${{ github.repository }}" >> $GITHUB_ENV
        echo "BRANCH_PATH=${{ github.ref }}" >> $GITHUB_ENV
        echo "BASE_URL=${${{ inputs.SERVER_URL }}%/}" >> $GITHUB_ENV
        echo "DOCASSEMBLE_DEVELOPER_API_KEY=${{ inputs.DOCASSEMBLE_DEVELOPER_API_KEY }}" >> $GITHUB_ENV
        echo "ALKILN_VERSION=${{ inputs.ALKILN_VERSION }}" >> $GITHUB_ENV
        echo "SERVER_RELOAD_TIMEOUT_SECONDS=${{ inputs.SERVER_RELOAD_TIMEOUT_SECONDS }}" >> $GITHUB_ENV
        # Default max value of 30 seconds for setup
        echo "MAX_SECONDS_FOR_SETUP=${{ inputs.MAX_SECONDS_FOR_SETUP || env.MAX_SECONDS_FOR_SETUP || 30 }}" >> $GITHUB_ENV
        echo "_ORIGIN=github" >> $GITHUB_ENV
      shell: bash
    - run: echo TEST is ${{ env.TEST }}
    - name: "ALKiln setup info: confirm environment variables"
      run: |
        # ALKiln setup info: confirm environment variables
        echo -e "\nALKiln version is $ALKILN_VERSION\nRepo is $REPO_URL\nBranch ref is $BRANCH_PATH\nMAX_SECONDS_FOR_SETUP is $MAX_SECONDS_FOR_SETUP\nSERVER_RELOAD_TIMEOUT_SECONDS is $SERVER_RELOAD_TIMEOUT_SECONDS\n"
      shell: bash

    # Install
    - name: "ALKiln setup info: Install node packages"
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Install ALKiln directly from npm
      run: |
        # ALKiln setup info: Install ALKiln directly from npm
        npm install -g @suffolklitlab/alkiln@$ALKILN_VERSION
      shell: bash

    # Install on playground

    # Don't rely on the environment's version of python
    - uses: actions/setup-python@v4
      if: ${{ inputs.INSTALL_METHOD == 'playground' }}
      with:
        python-version: '3.10'
    - name: "ALKiln: Create a Project and install the package from GitHub"
      if: ${{ inputs.INSTALL_METHOD == 'playground' }}
      run: |
        # ALKiln setup info: Create a Project and install the package from GitHub
        pip3 install docassemblecli
        # Installs to the Playground via the node commandline
        alkiln-setup
      shell: bash
    - name: "ALKiln setup ERROR"
      run: echo -e "\n\n====\nALKiln ERROR - could not create a project on your server's testing account or pull your package into it. Check the messages above this line.\n\n"
      if: ${{ inputs.INSTALL_METHOD == 'playground' && failure() }}
      shell: bash

    # Server installations - find folders and save session vars
    - name: "ALKiln setup info: Install the GitHub package onto the server"
      if: ${{ inputs.INSTALL_METHOD == 'server' }}
      # Checks the repo package folder and saves some env vars
      # The user should have done the actual package installation earlier when creating the server
      run: alkiln-server-install
      shell: bash
    - name: "ALKiln setup ERROR"
      run: echo -e "\n\n====\nALKiln ERROR - could not install the package on the temporary GitHub docassemble server. Check the steps above this line.\n\n"
      if: ${{ inputs.INSTALL_METHOD == 'server' && failure() }}
      shell: bash

    # wait for server to reload if necessary
    - name: "ALKiln info: Wait for modules to install"
      if: ${{ success() }}
      shell: bash
      run: |
        # ALKiln: Wait for project to install
        echo MAX_SECONDS_FOR_SETUP is ${{ env.MAX_SECONDS_FOR_SETUP }}

        # Reset the SECONDS variable, a built-in bash variable that
        # increments itself
        SECONDS=0
        sleep_time=5

        response="start"
        while [[ $response != *"200"* ]]; do
          echo "ALKiln setup: Time elapsed: $SECONDS seconds"

          # Check if max seconds till loading has passed
          if [[ $SECONDS -ge ${{ env.MAX_SECONDS_FOR_SETUP }} ]]; then
            echo "ALKiln setup Error: Timed out waiting for the server to reload after installing the package. If you want to give your server more timem to reload, set the MAX_SECONDS_FOR_SETUP input for this action to a higher value than ${{ env.MAX_SECONDS_FOR_SETUP }}."
            exit 1
          fi

          # Ask the server if it's ready
          response=$(curl -o /dev/null -s -w "%{http_code}\n" ${{ env.BASE_URL }}/health_check?ready=1)
          echo "ALKiln setup: server response to health_check is $response"

          # If the server is ready, finish, otherwise pause and then try again
          if [[ $response == *"200"* ]]; then
            echo "ALKiln Success! The docassemble server has uploaded your package!"
          else
            echo "ALKiln setup: Your package upload is not yet finished. This is try number $(( $SECONDS / $sleep_time )) of $(( ${{ env.MAX_SECONDS_FOR_SETUP }} / $sleep_time )). Will check again in $sleep_time seconds."
            sleep $sleep_time
          fi
        done

    # run tests
    - name: "ALKiln info: Run tests"
      if: ${{ success() }}
      run: alkiln-run ${{ inputs.ALKILN_TAG_EXPRESSION || github.event.inputs.tags && format('{0}', github.event.inputs.tags) }}
      shell: bash
    
    # on playground, delete project
    - name: "ALKiln info: Try to delete the project from the playground of the docassemble test account."
      if: ${{ inputs.INSTALL_METHOD == 'playground' }}
      run: alkiln-takedown
      shell: bash
    
    # Upload artifacts that subscribers can download on the Actions summary page
    - name: "ALKiln info: Upload artifacts folder"
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./alkiln-*

    - run: echo "ALkiln finished running tests"
      shell: bash

# ##################################
# # A developer's workflow should look similar to the below.
# # In place of `uses: suffolkLITLab/ALKiln@v5`, they
# # might use another version.
#
# name: ALKiln v5 tests
# on:
#   push:
#   workflow_dispatch:
#     inputs:
#       tags:
#         description: 'Optional. Use a "tag expression" specify which tagged tests to run. See https://cucumber.io/docs/cucumber/api/#tag-expressions for syntax.'
#         default: ''
#
# jobs:
#
#   interview-testing:
#     runs-on: ubuntu-latest
#     name: Run interview tests
#     steps:
#       - name: Use ALKiln to run tests
#         uses: suffolkLITLab/ALKiln@v5
#         with:
#           SERVER_URL: "${{ secrets.SERVER_URL }}"
#           DOCASSEMBLE_DEVELOPER_API_KEY: "${{ secrets.DOCASSEMBLE_DEVELOPER_API_KEY }}"
